begin;

create table if not exists public.jaen_streets (
  id bigserial primary key,
  source_code int not null,
  via_type text not null check (char_length(via_type) between 1 and 6),
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_jaen_streets_source on public.jaen_streets(source_code, via_type, name);
create index if not exists idx_jaen_streets_name on public.jaen_streets(lower(name));

create table if not exists public.street_closures (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  closure_date date not null default current_date,
  street_id bigint not null references public.jaen_streets(id) on update cascade on delete restrict,
  status text not null default 'activa' check (status in ('activa','resuelta')),
  reason text,
  reported_by text,
  resolved_at timestamptz,
  resolved_by text
);

create index if not exists idx_street_closures_date_status on public.street_closures(closure_date desc, status);
create index if not exists idx_street_closures_street on public.street_closures(street_id);

alter table public.jaen_streets enable row level security;
alter table public.street_closures enable row level security;

grant usage on schema public to authenticated;
grant select on table public.jaen_streets to authenticated;
grant select, insert, update on table public.street_closures to authenticated;
grant delete on table public.street_closures to authenticated;

drop policy if exists "jaen_streets_select_auth" on public.jaen_streets;
create policy "jaen_streets_select_auth"
  on public.jaen_streets for select to authenticated using (true);

drop policy if exists "street_closures_select_auth" on public.street_closures;
create policy "street_closures_select_auth"
  on public.street_closures for select to authenticated using (true);

drop policy if exists "street_closures_insert_edit" on public.street_closures;
create policy "street_closures_insert_edit"
  on public.street_closures for insert to authenticated with check (public.app_can_edit());

drop policy if exists "street_closures_update_edit" on public.street_closures;
create policy "street_closures_update_edit"
  on public.street_closures for update to authenticated
  using (public.app_can_edit()) with check (public.app_can_edit());

drop policy if exists "street_closures_delete_admin" on public.street_closures;
create policy "street_closures_delete_admin"
  on public.street_closures for delete to authenticated using (public.app_is_admin());

-- Calles de Jaén cargadas desde 0_1665_1.pdf
insert into public.jaen_streets(source_code, via_type, name) values
  (1, 'CL', 'Abades'),
  (4506, 'PZ', 'Acho (del)'),
  (3, 'CL', 'Adarves Altos'),
  (4, 'CL', 'Adarves Bajos'),
  (4796, 'CL', 'Adelantado (del)'),
  (5, 'CL', 'Agustín Rodenas'),
  (6, 'CL', 'Agustina de Aragón'),
  (4354, 'CI', 'Agustina de Aragón'),
  (7, 'CL', 'Aire'),
  (8, 'CL', 'Alameda de Calvo Sotelo'),
  (9, 'CL', 'Alamos'),
  (4171, 'CL', 'Alberca (de La)'),
  (3959, 'CJ', 'Alcaide (del)'),
  (4522, 'CL', 'Alcalá la Real'),
  (11, 'CL', 'Alcalá Wenceslada'),
  (12, 'CL', 'Alcalde Cancio Uribe'),
  (3955, 'PJ', 'Alcalde Cancio Uribe'),
  (4852, 'CL', 'Alcalde Emilio Arroyo López'),
  (3956, 'CL', 'Alcalde Fiestas Rodríguez'),
  (4490, 'RD', 'Alcalde García Segovia'),
  (4851, 'CL', 'Alcalde José María de la Torre Colmenero'),
  (3957, 'CL', 'Alcalde Montón Civera'),
  (3940, 'CL', 'Alcalde Morales Robles'),
  (3958, 'CL', 'Alcalde Pancorbo Ortuño'),
  (4200, 'CL', 'Alcalde Velasco Pro'),
  (4224, 'CL', 'Alcaudete'),
  (4273, 'CJ', 'Alcázar (del)'),
  (15, 'CL', 'Alcázar de Toledo'),
  (16, 'CL', 'Aldana'),
  (17, 'CL', 'Alegría'),
  (18, 'CL', 'Alféreces Provisionales'),
  (19, 'CL', 'Alférez Rojas Navarrete'),
  (20, 'CL', 'Alférez Segura'),
  (21, 'CL', 'Alguacil'),
  (4523, 'CL', 'Alhama'),
  (4524, 'CL', 'Alicante'),
  (23, 'CL', 'Almagro'),
  (4491, 'SN', 'Almenara (Almenara)'),
  (24, 'CL', 'Almenas'),
  (4489, 'CL', 'Almendros (los)'),
  (25, 'CL', 'Almendros Aguilar'),
  (27, 'CL', 'Almería'),
  (90027, 'CL', 'Almería (Pte. Tablas)'),
  (4704, 'CL', 'Almetriches (de los)'),
  (28, 'CL', 'Almodovar'),
  (4759, 'CL', 'Alonso Barba'),
  (4436, 'CL', 'Alta de Santa Ana'),
  (30, 'CL', 'Alto de los Leones'),
  (31, 'CL', 'Alvarez'),
  (4910, 'CL', 'Ana de Grananda'),
  (4829, 'CL', 'Ana Mª Nogueras'),
  (4908, 'CL', 'Ana Rodríguez'),
  (4163, 'AV', 'Andalucía'),
  (4404, 'CL', 'Andorra'),
  (34, 'CL', 'Andrés Segovia'),
  (35, 'CL', 'Andújar'),
  (36, 'CL', 'Angel María Arregui'),
  (4802, 'CL', 'Ángel Martín Miñano'),
  (4488, 'CL', 'Angeles (los)'),
  (38, 'CL', 'Antón de Cuellar'),
  (4800, 'CL', 'Antonio Almendros Soto (de)'),
  (4879, 'CL', 'Antonio Collado Almazán'),
  (4781, 'CL', 'Antonio de Lara Gavilán Tono'),
  (4755, 'CL', 'Antonio de las Viñas'),
  (3951, 'CL', 'Antonio Delgado Anguita'),
  (4642, 'CL', 'Antonio Díaz'),
  (4643, 'CL', 'Antonio Herrera Murillo'),
  (4838, 'CL', 'Antonio Muñoz Molina'),
  (4876, 'CL', 'Antonio Romero Maroto'),
  (3963, 'CL', 'Apolo'),
  (4774, 'CL', 'Aragón (de)'),
  (41, 'CL', 'Arco de los Dolores'),
  (43, 'CL', 'Arco del Consuelo'),
  (3964, 'CL', 'Arco Puerta de Granada'),
  (46, 'AV', 'Arjona (de)'),
  (47, 'CL', 'Arquillos'),
  (48, 'CL', 'Arquitecto Berges'),
  (4885, 'CL', 'Arquitecto José Gallego'),
  (4857, 'CL', 'Arquitecto Juan de Aranda Salazar'),
  (4859, 'CL', 'Arquitecto Pablo del Castillo García-Negrete'),
  (49, 'CL', 'Arrastradero'),
  (50, 'CL', 'Arroyo de San Pedro'),
  (4694, 'SN', 'Arroyo Valparaiso (Pte. Sierra)'),
  (51, 'CL', 'Artesanos'),
  (4527, 'CL', 'Asdrubal'),
  (52, 'CL', 'Astorga'),
  (53, 'CL', 'Atarazanas'),
  (4487, 'PZ', 'Audiencia (de la)'),
  (4424, 'CL', 'Avellano'),
  (4528, 'CL', 'Avila'),
  (58, 'CL', 'Ayuntamiento'),
  (59, 'CL', 'Azulejos'),
  (3984, 'CL', 'Baeza'),
  (62, 'CL', 'Bailen'),
  (4644, 'CR', 'Bailen-Motril'),
  (94644, 'CR', 'Bailen-Motril (Las Infantas)'),
  (4144, 'SN', 'Balcón (El) (Pte. Sierra)'),
  (3986, 'SN', 'Balneario de Jabalcuz (Jabalcuz)'),
  (3980, 'CL', 'Baltasar de Alcázar'),
  (4159, 'AV', 'Barcelona (de)'),
  (3979, 'CL', 'Barranco de la Alcantarilla'),
  (67, 'CL', 'Barranco de la Coronada'),
  (68, 'CL', 'Batalla de Bailen'),
  (69, 'CL', 'Batalla de Brunete'),
  (70, 'CL', 'Batalla del Ebro'),
  (4486, 'PZ', 'Batallas (de las)'),
  (72, 'CL', 'Batería'),
  (73, 'CL', 'Bazo'),
  (60, 'CL', 'Baños de la Audiencia'),
  (4710, 'CL', 'Baños de la Encina'),
  (4899, 'CL', 'Beatriz Nuñez'),
  (3995, 'CL', 'Beas de Segura'),
  (4711, 'CL', 'Begijar'),
  (4160, 'PZ', 'Belén (de)'),
  (4712, 'CL', 'Belmez de la Moraleda'),
  (4809, 'CL', 'Ben Saprut (de)'),
  (4814, 'CL', 'Benatae'),
  (76, 'CL', 'Berberiscos'),
  (4148, 'SN', 'Berenguel (El) (Pte. Sierra)'),
  (77, 'CL', 'Bernabé Soriano'),
  (78, 'CL', 'Bernardas (las)'),
  (79, 'CL', 'Bernardo López'),
  (4645, 'CL', 'Bernardo Ruiz Cano'),
  (81, 'CL', 'Betania'),
  (4646, 'CL', 'Bilbao'),
  (4647, 'GT', 'Blas Infante (de)'),
  (83, 'CL', 'Bobadilla Alta'),
  (4258, 'TR', 'Bobadilla Alta Primera'),
  (4265, 'TR', 'Bobadilla Alta Segunda'),
  (84, 'CL', 'Bobadilla Baja'),
  (86, 'CL', 'Borja'),
  (4028, 'SN', 'Brujuelo (Brujuelo)'),
  (87, 'CL', 'Buenavista'),
  (88, 'CL', 'Buenos Aires'),
  (4801, 'CL', 'Burgos (de)'),
  (4531, 'CL', 'Cabrerizas Altas'),
  (93, 'CL', 'Cabrerizas Bajas'),
  (95, 'CL', 'Cádiz'),
  (90095, 'CL', 'Cádiz (Pte. Tablas)'),
  (4399, 'TR', 'Calle La Corona Primera'),
  (4400, 'TR', 'Calle La Corona Segunda'),
  (97, 'CL', 'Calvache'),
  (98, 'CL', 'Calvario'),
  (99, 'CL', 'Camarín de Jesús'),
  (100, 'CL', 'Cambil'),
  (101, 'PZ', 'Cambil'),
  (102, 'CL', 'Cambroneras'),
  (104, 'CL', 'Campanas'),
  (105, 'CL', 'Campanas De Santiago'),
  (4766, 'CL', 'Canarias (de)'),
  (106, 'CL', 'Candido Carpio'),
  (4402, 'CL', 'Candido Méndez'),
  (4708, 'CL', 'Canena'),
  (4881, 'CL', 'Canónigo Fernando Gallardo Carpio'),
  (4776, 'CL', 'Cantabria (de)'),
  (107, 'CL', 'Cantaor Canalejas'),
  (108, 'CL', 'Cantaor Marchena'),
  (4844, 'CL', 'Cantaora Rosario López'),
  (109, 'CL', 'Cantareros'),
  (110, 'TR', 'Cantareros'),
  (4435, 'CL', 'Cantón de Santa Ana'),
  (112, 'CL', 'Capitán Aranda Alta'),
  (113, 'CL', 'Capitán Aranda Baja'),
  (114, 'CL', 'Capitán Cortes'),
  (115, 'CL', 'Capitán Haya'),
  (116, 'CL', 'Capitán Oviedo'),
  (117, 'CL', 'Capitán Palacios'),
  (4825, 'CL', 'Capuchino'),
  (4706, 'CL', 'Cardenal Marcelo Spinola (del)'),
  (118, 'CL', 'Cárdenas'),
  (119, 'CL', 'Caridad'),
  (120, 'CL', 'Carlos V'),
  (121, 'CL', 'Carmelo Torres'),
  (4482, 'CL', 'Carmen (el)'),
  (4842, 'CL', 'Carmen de Michelena'),
  (4887, 'CL', 'Carmona'),
  (123, 'CL', 'Carnero'),
  (124, 'CL', 'Carniceros'),
  (4648, 'CL', 'Carolina (la)'),
  (126, 'CL', 'Carrera de Jesús'),
  (4532, 'CL', 'Carretas'),
  (3905, 'SN', 'Casería Almodovar'),
  (4191, 'SN', 'Casería Casa Grande (Pte. Sierra)'),
  (4127, 'SN', 'Casería Doctoral (Puerto Alto)'),
  (4150, 'SN', 'Casería El Carmen (Pte. Sierra)'),
  (4141, 'SN', 'Casería El Duende (Galapagar)'),
  (4406, 'SN', 'Casería Fuente Bonora (Pte. Sierra)'),
  (4412, 'SN', 'Casería La Bermeja (Pte. Sierra)'),
  (3890, 'SN', 'Casería La Ermita (Jabalcuz)'),
  (4686, 'SN', 'Casería Las Olivas (Pte. Sierra)'),
  (4369, 'SN', 'Casería Nueva (Pte. Sierra)'),
  (3910, 'SN', 'Casería Ochoa (Jabalcuz)'),
  (4685, 'SN', 'Casería Peña Del Gato (Pte. Sierra)'),
  (4684, 'SN', 'Casería Pililas (las) (Pte. Sierra)'),
  (3858, 'SN', 'Casería San Sebastián (Jabalcuz)'),
  (4386, 'SN', 'Casería Santo Cristo (Pte. Sierra)'),
  (908, 'SN', 'Caserío Virgen del Carmen (Pte. Sierra)'),
  (4425, 'CL', 'Castaño'),
  (4707, 'CL', 'Castellar'),
  (130, 'CL', 'Castilla'),
  (4767, 'CL', 'Castilla y León (de)'),
  (4777, 'CL', 'Castilla la Mancha (de)'),
  (4533, 'CL', 'Castillo de Jaen'),
  (4836, 'CL', 'Catalina Mir Real'),
  (4768, 'CL', 'Cataluña (de)'),
  (4709, 'CL', 'Cazalilla'),
  (131, 'CL', 'Cazorla'),
  (4702, 'CL', 'Cañizares'),
  (4744, 'SN', 'Caño Quebrado (Caño Quebrado)'),
  (4483, 'PZ', 'Caños (los)'),
  (4484, 'CL', 'Caños (los)'),
  (91, 'CL', 'Cañuelo de Jesús'),
  (133, 'CL', 'Celadores'),
  (4380, 'SN', 'Centro Penitenciario Jaen II (Grañena)'),
  (134, 'CL', 'Cerón'),
  (135, 'CL', 'Cerrillo de la Misericordia'),
  (4381, 'SN', 'Cerro de las Canteras'),
  (4783, 'CL', 'Cerro de los Lirios'),
  (4811, 'CL', 'Cerro de San Cristóbal (Del)'),
  (4187, 'SN', 'Cerro Molina (Pte. Nuevo)'),
  (4339, 'UR', 'Cerro Molina (Pte. Nuevo)'),
  (1604, 'SN', 'Cerro Moreno (Pte. Nuevo)'),
  (136, 'PZ', 'Cervantes'),
  (4553, 'CL', 'Ceuta (de)'),
  (94553, 'CL', 'Ceuta (Pte. Tablas)'),
  (4383, 'CL', 'Chartes'),
  (4713, 'CL', 'Chiclana de Segura'),
  (138, 'CL', 'Chile'),
  (4714, 'CL', 'Chilluevar'),
  (139, 'CL', 'Chinchilla'),
  (141, 'CL', 'Cid Campeador'),
  (4810, 'CL', 'Cierzo (del)'),
  (142, 'CL', 'Ciprés'),
  (143, 'CR', 'Circunvalación'),
  (4855, 'CL', 'Clara Campoamor'),
  (144, 'CL', 'Clavel'),
  (145, 'PZ', 'Coca de la Piñera'),
  (146, 'CL', 'Colegio'),
  (147, 'CL', 'Colon'),
  (148, 'CL', 'Comandante Roman'),
  (149, 'TR', 'Comandante Roman'),
  (494, 'CL', 'Compañía (de la)'),
  (4779, 'CL', 'Comunidad de Madrid (de la)'),
  (4682, 'SN', 'Comunidad El Vivero (Pte. Jontoya)'),
  (4780, 'CL', 'Comunidad Foral de Navarra (de la)'),
  (4773, 'CL', 'Comunidad Valenciana (de la)'),
  (4864, 'CL', 'Concejal Rosario Ramírez Mora'),
  (4856, 'CL', 'Concepción Arenal'),
  (151, 'CL', 'Concepción Vieja'),
  (4850, 'CL', 'Concha Espina'),
  (152, 'CL', 'Conde'),
  (153, 'CL', 'Condesa'),
  (154, 'CL', 'Condestable Iranzo'),
  (155, 'TR', 'Condestable Iranzo'),
  (4909, 'CL', 'Constanza Guillén'),
  (4480, 'PZ', 'Constitución (de la)'),
  (157, 'CL', 'Contreras'),
  (4535, 'CL', 'Cora'),
  (158, 'PZ', 'Corazón de María'),
  (159, 'CL', 'Córdoba'),
  (90159, 'CL', 'Córdoba (Pte. Tablas)'),
  (10010, 'CR', 'Córdoba-Valencia'),
  (4499, 'CL', 'Corona (de la)'),
  (4505, 'PZ', 'Corona (de la)'),
  (977, 'CL', 'Correa Weglison'),
  (163, 'CL', 'Corregidores'),
  (4358, 'SN', 'Cortijo Cuarterones (Puerto Alto)'),
  (2272, 'SN', 'Cortijo El Manzano (Las Infantas)'),
  (4690, 'SN', 'Cortijo Fuente Tetar (Ventosilla)'),
  (1616, 'SN', 'Cortijo Racioneros (Brujuelo)'),
  (2260, 'SN', 'Cortijo Santa Ana (Las Infantas)'),
  (4815, 'CL', 'Coruña'),
  (4787, 'CL', 'Costa Rica'),
  (4649, 'CL', 'Cristo de la Clemencia'),
  (4370, 'CL', 'Cristo de los Chircales'),
  (165, 'CL', 'Cristo Rey'),
  (166, 'CL', 'Cronista Cazaban'),
  (167, 'CL', 'Cronista González López'),
  (4479, 'CM', 'Cruces (las)'),
  (168, 'CL', 'Cruz de la Magdalena'),
  (4259, 'TR', 'Cruz de la Magdalena Primera'),
  (4650, 'CJ', 'Cruz de la Magdalena Primero'),
  (4266, 'TR', 'Cruz de la Magdalena Segunda'),
  (4651, 'CJ', 'Cruz de la Magdalena Segundo'),
  (2057, 'CL', 'Cruz Roja Española'),
  (4478, 'PZ', 'Cruz Rueda'),
  (4652, 'CL', 'Cruz Salido'),
  (4477, 'CL', 'Cruzada (la)'),
  (172, 'CL', 'Cuartel de Simancas'),
  (173, 'CL', 'Cuatro Torres'),
  (174, 'CL', 'Cuatro Vientos'),
  (4485, 'CL', 'Cuesta de Belén'),
  (4442, 'CL', 'Cuesta de la Virgen'),
  (4434, 'CL', 'Cuesta de San Miguel'),
  (4476, 'TR', 'Cuesta del Molinillo'),
  (4453, 'CL', 'Cuesta del Molinillo'),
  (4817, 'CL', 'Cuesta del Tocinillo'),
  (4475, 'CL', 'Cumbres (las)'),
  (4474, 'CL', 'Cuna (la)'),
  (179, 'PZ', 'Curtidores'),
  (4521, 'TR', 'Curtidores'),
  (180, 'CL', 'Deán de la Fuente González'),
  (4292, 'PZ', 'Deán Mazas'),
  (4786, 'CL', 'Diario Jaén'),
  (183, 'CL', 'Dieciocho de Julio'),
  (10011, 'SN', 'Diseminados'),
  (4653, 'CL', 'División Azul'),
  (185, 'CL', 'Doce Apóstoles'),
  (4420, 'PR', 'Doctor Azpitarte'),
  (4654, 'CL', 'Doctor Azpitarte'),
  (4655, 'CL', 'Doctor Benedicto'),
  (4656, 'TR', 'Doctor Benedicto Primera'),
  (4657, 'TR', 'Doctor Benedicto Segunda'),
  (3349, 'PZ', 'Doctor Blanco Najera'),
  (191, 'CL', 'Doctor Carlos Carbonell'),
  (192, 'CL', 'Doctor Civera'),
  (186, 'CL', 'Doctor Eduardo Arroyo'),
  (4740, 'CL', 'Doctor Eduardo García-Triviño López'),
  (2365, 'CL', 'Doctor Federico del Castillo'),
  (193, 'CL', 'Doctor Fleming'),
  (194, 'CL', 'Doctor García Anguita'),
  (195, 'CL', 'Doctor García Jiménez'),
  (4658, 'CL', 'Doctor Gómez Duran'),
  (197, 'CL', 'Doctor Gómez Ulla'),
  (198, 'CL', 'Doctor Juan Nogales'),
  (199, 'CL', 'Doctor Luzón'),
  (200, 'CL', 'Doctor Marañón'),
  (4659, 'CL', 'Doctor Martínez Bordiu'),
  (4804, 'CL', 'Doctor Pedro Quesada Martínez (del)'),
  (4798, 'CL', 'Doctor Ramiro Rivera'),
  (3889, 'CL', 'Doctor Rodríguez de la Fuente'),
  (3493, 'CL', 'Doctor Sánchez de la Nieta'),
  (4660, 'CL', 'Doctor Severo Ochoa'),
  (4698, 'CL', 'Don Rafael Ortega Sagrista'),
  (4350, 'CL', 'Donantes de Sangre'),
  (4443, 'CL', 'Dos de Mayo'),
  (4167, 'GT', 'Doña Lola Torres (de)'),
  (4833, 'CL', 'Dr. Bueno Fafardo'),
  (4865, 'CL', 'Dr. Eduardo Balguerías'),
  (4845, 'CL', 'Dr. José Montilla Bono'),
  (4877, 'CL', 'Dr. Pío Aguirre Rodríguez'),
  (204, 'CL', 'Duende de la Magdalena'),
  (205, 'CL', 'Duque'),
  (208, 'AV', 'Ejercito Español'),
  (210, 'CL', 'Ejido de la Alcantarilla'),
  (211, 'CL', 'Elvin'),
  (4853, 'CL', 'Embajador José Luis Messia Jiménez'),
  (212, 'CL', 'Empedrada de la Magdalena'),
  (4427, 'CL', 'Encina'),
  (4603, 'CL', 'Enrique Ponce'),
  (3943, 'SN', 'Era de Valdelimones (Jabalcuz)'),
  (214, 'CL', 'Eras de Belén'),
  (213, 'CL', 'Eras de la Alcantarilla'),
  (215, 'CL', 'Eras de Santa Ana'),
  (217, 'PZ', 'Escalerillas'),
  (216, 'CL', 'Escalerillas'),
  (4715, 'CL', 'Escañuela'),
  (4661, 'CL', 'Escorial'),
  (220, 'CL', 'Escuderos'),
  (4764, 'PS', 'España (de)'),
  (2257, 'CL', 'Espeluy'),
  (4473, 'CL', 'Esperanza (la)'),
  (293, 'CL', 'Espiga'),
  (4471, 'PS', 'Estación (de la)'),
  (4828, 'CL', 'Esteban Ramírez Martínez'),
  (4760, 'CL', 'Eufrasio López de Rojas'),
  (4538, 'CL', 'Europa'),
  (4778, 'CL', 'Extremadura (de)'),
  (226, 'CL', 'Fajardo'),
  (228, 'CL', 'Federico de Mendizabal'),
  (4539, 'PZ', 'Federico García Lorca'),
  (4827, 'CL', 'Federico Mayor Zaragoza'),
  (4846, 'CL', 'Felipe Oya Rodríguez'),
  (229, 'CL', 'Fermín Palma'),
  (230, 'CL', 'Fernando IV'),
  (1622, 'SN', 'Finca del Huevo (Brujuelo)'),
  (1639, 'SN', 'Finca el Ventorrillo (Pte. Nuevo)'),
  (4133, 'SN', 'Finca Torremocha (Pte. Nuevo)'),
  (1579, 'SN', 'Finca Villa Ascensión (Pte. Nuevo)'),
  (4472, 'SN', 'Finca Villa Luz (Pte. Sierra)'),
  (4366, 'SN', 'Finca Villa Paula (Las Infantas)'),
  (4469, 'CJ', 'Flores (las)'),
  (232, 'CL', 'Flores de Lemus'),
  (4840, 'CL', 'Fotógrafo Jaime Roselló'),
  (4681, 'PA', 'Fraila (la)(Pte. Jontoya)'),
  (4716, 'CL', 'Frailes'),
  (233, 'CL', 'Francisco Coello'),
  (2279, 'CL', 'Francisco del Moral (Las Infantas)'),
  (234, 'CL', 'Francisco López Huertas'),
  (4492, 'CL', 'Francisco Martín Mora'),
  (4018, 'CL', 'Francisco Rodríguez Acosta'),
  (4782, 'CL', 'Francisco Tomas y Valiente'),
  (236, 'CL', 'Frente a Jesús'),
  (4717, 'CL', 'Fuensanta de Martos'),
  (4513, 'CL', 'Fuente de Buenora'),
  (237, 'CL', 'Fuente de Don Diego'),
  (890, 'TR', 'Fuente de Don Diego'),
  (4735, 'CL', 'Fuente de la Imora'),
  (4732, 'CL', 'Fuente de la Mimbre'),
  (238, 'CM', 'Fuente de la Peña'),
  (4697, 'CL', 'Fuente de la Plata'),
  (4512, 'CL', 'Fuente de la Salud'),
  (4510, 'CL', 'Fuente de la Zarza'),
  (4820, 'CL', 'Fuente de las Doncellas'),
  (4511, 'CL', 'Fuente de los Corzos'),
  (4736, 'CL', 'Fuente del Alamillo'),
  (4696, 'CL', 'Fuente del Arca'),
  (4737, 'CL', 'Fuente del Moralejo'),
  (4734, 'CL', 'Fuente del Peral'),
  (4733, 'CL', 'Fuente del Pinillo'),
  (4738, 'CL', 'Fuente del Serbo'),
  (4497, 'CL', 'Fuente Nueva'),
  (2485, 'CL', 'Fuerte del Rey'),
  (2188, 'CR', 'Fuerte del Rey'),
  (92188, 'CR', 'Fuerte del Rey (Villar De Cuevas)'),
  (3845, 'CL', 'Gacela'),
  (1602, 'SN', 'Galapagar (Galapagar)'),
  (4770, 'CL', 'Galicia (de)'),
  (240, 'CL', 'García Morente'),
  (241, 'CL', 'García Rebull'),
  (242, 'CL', 'García Requena'),
  (4297, 'CJ', 'Gato (del)'),
  (4763, 'CL', 'Genave'),
  (244, 'CL', 'General Castaños'),
  (245, 'TR', 'General Castaños'),
  (246, 'CL', 'General Chamorro'),
  (247, 'PZ', 'General Moscardo'),
  (4298, 'RD', 'General Rodrigo'),
  (10000, 'UR', 'Glorieta (la)'),
  (248, 'CL', 'Goya'),
  (249, 'CL', 'Gracia'),
  (250, 'CL', 'Gracianas'),
  (4543, 'CL', 'Gran Capitán'),
  (1279, 'CR', 'Granada'),
  (4372, 'CL', 'Granada'),
  (4162, 'AV', 'Granada'),
  (94372, 'CL', 'Granada (Pte. Tablas)'),
  (4468, 'CL', 'Granja (la)'),
  (254, 'CL', 'Greco (el)'),
  (255, 'CL', 'Gregorio Murcia'),
  (257, 'CL', 'Guadalbullon'),
  (258, 'CL', 'Guadalquivir'),
  (4025, 'CR', 'Guardia (la)'),
  (94025, 'CR', 'Guardia (la) (Pte. Jontoya)'),
  (259, 'CL', 'Guatemala (de)'),
  (4883, 'CL', 'Henry Dunant'),
  (4520, 'CL', 'Hermana Esperanza'),
  (4873, 'CL', 'Hermanos Álamo Berzosa'),
  (4544, 'CL', 'Hermanos Espejo Tortosa'),
  (261, 'CL', 'Hermanos Pinzón'),
  (4758, 'CL', 'Hermanos Senise Colmenero'),
  (488, 'PZ', 'Hermenegildo Terrados (de)'),
  (4663, 'CL', 'Hernán Cortes'),
  (4664, 'CL', 'Herrerias'),
  (4746, 'SN', 'Herrerias (las) (Cañoquebrado)'),
  (264, 'CL', 'Hervas'),
  (4719, 'CL', 'Higuera de Arjona'),
  (4467, 'CL', 'Higueras (las)'),
  (4854, 'CL', 'Himilce'),
  (4720, 'CL', 'Hinojares'),
  (4862, 'CL', 'Historiador Juan de Mata Carriaza'),
  (4466, 'CL', 'Horno de los Caños'),
  (787, 'CL', 'Horno Puerta de Granada'),
  (269, 'CL', 'Hornos Franco'),
  (270, 'CL', 'Hornos Mirez'),
  (271, 'CL', 'Hornos Negros'),
  (4502, 'CL', 'Hornos Santiago'),
  (4818, 'CL', 'Hospital de San Lázaro'),
  (272, 'CL', 'Hospital de San Miguel'),
  (273, 'CL', 'Hospitalico'),
  (4135, 'CL', 'Huelma'),
  (274, 'CL', 'Huelva'),
  (90274, 'CL', 'Huelva (Pte. Tablas)'),
  (4465, 'CL', 'Huérfanos (los)'),
  (4743, 'CL', 'Huerta Baja'),
  (370, 'CL', 'Huerta de la Calatrava'),
  (4146, 'SN', 'Huerta la Vereda (Pte. Sierra)'),
  (4192, 'CM', 'Huertas (de las)(Pte. Sierra)'),
  (4464, 'CL', 'Huertas (las)'),
  (4721, 'CL', 'Huesa'),
  (278, 'CL', 'Hurtado'),
  (4731, 'CL', 'Ibros'),
  (279, 'CL', 'Ignacio Figueroa'),
  (2864, 'SN', 'Imora (la)(La Imora)'),
  (4364, 'CL', 'Infanta Amelia (Las Infantas)'),
  (2200, 'CL', 'Infanta Beatriz (Las Infantas)'),
  (4679, 'PZ', 'Infanta Cristina (de la)(Las Infantas)'),
  (4470, 'AV', 'Infanta Elena (de la)(Las Infantas)'),
  (2288, 'CL', 'Infanta Isabel (Las Infantas)'),
  (4363, 'CL', 'Infanta Luisa Fernanda (Las Infantas)'),
  (4678, 'CL', 'Infanta Margarita (Las Infantas)'),
  (2234, 'CL', 'Infanta María Cristina (Las Infantas)'),
  (4365, 'CL', 'Infanta María de las Mercedes (Las Infantas)'),
  (2284, 'CL', 'Infanta María Teresa (Las Infantas)'),
  (4407, 'CL', 'Infanta Paz (Las Infantas)'),
  (4677, 'CL', 'Infanta Pilar (Las Infantas)'),
  (2216, 'SN', 'Infantas (Las)(Las Infantas)'),
  (4875, 'CL', 'Ingeniero José María Almendral Lucas'),
  (281, 'CL', 'Inspector Molinos'),
  (4722, 'CL', 'Iruela (la)'),
  (282, 'CL', 'Isaac Albeniz'),
  (283, 'CL', 'Isaac Peral'),
  (284, 'CL', 'Isabel Méndez'),
  (4775, 'CL', 'Islas Baleares (de las)'),
  (4723, 'CL', 'Iznatoraf'),
  (286, 'CR', 'Jabalcuz'),
  (2862, 'SN', 'Jabalcuz (Jabalcuz)'),
  (4515, 'CL', 'Jabalquinto'),
  (287, 'CL', 'Jaboneras'),
  (288, 'CL', 'Jacinto Benavente'),
  (289, 'CL', 'Jacinto Higueras'),
  (4360, 'CL', 'Jaen'),
  (94360, 'CL', 'Jaen (Pte. Tablas)'),
  (4481, 'PZ', 'Jaen por la Paz'),
  (4724, 'CL', 'Jamilena'),
  (4462, 'SN', 'Jardín del Obispo'),
  (4695, 'UR', 'Jardín Puente Tablas'),
  (4509, 'CL', 'Jardín Villa Rosario'),
  (4508, 'TR', 'Jardín Villa Rosario'),
  (1089, 'CL', 'Jardines del Campo Hípico'),
  (4463, 'PZ', 'Jardinillos (de los)'),
  (292, 'CL', 'Jesús'),
  (4725, 'CL', 'Jimena'),
  (294, 'CL', 'Joaquín Costa'),
  (4550, 'CL', 'Joaquín Nogueras'),
  (296, 'CL', 'Joaquín Tenorio'),
  (4665, 'CL', 'Jorge Morales'),
  (299, 'CL', 'José Antonio Girón'),
  (300, 'TR', 'José Antonio Girón'),
  (4272, 'TR', 'José Antonio Girón Primera'),
  (4267, 'TR', 'José Antonio Girón Segunda'),
  (4551, 'CL', 'José López Tafall'),
  (303, 'CL', 'José María Padilla'),
  (4496, 'PZ', 'José Solis'),
  (306, 'CL', 'José Zorrilla'),
  (4554, 'PR', 'José Zorrilla'),
  (307, 'TR', 'José Zorrilla'),
  (308, 'CL', 'Josefa Segovia'),
  (309, 'CL', 'Josefa Sevillanos'),
  (4841, 'CL', 'Juan Eslava Galán'),
  (310, 'CL', 'Juan Montilla'),
  (4884, 'CL', 'Juan Pablo II'),
  (2388, 'CL', 'Juan Pedro Gutiérrez Higueras'),
  (4415, 'PA', 'Juan Ramos (Pte. Nuevo)'),
  (311, 'CL', 'Juan Rincón'),
  (312, 'CL', 'Juan Valera'),
  (313, 'CL', 'Juanito el Practicante'),
  (4867, 'CL', 'Juanito Valderrama'),
  (4799, 'RD', 'Juez Juan Ruiz Rico'),
  (4680, 'CL', 'Julian Torres (Las Infantas)'),
  (314, 'CL', 'Julio Angel'),
  (4756, 'CL', 'Justino Florez Llamas'),
  (4821, 'PZ', 'La Unión (de)'),
  (316, 'CL', 'Labradores'),
  (4558, 'CL', 'Laguna'),
  (4843, 'CL', 'Las Sufragistas'),
  (318, 'CL', 'Lavanderas'),
  (4904, 'CL', 'Leonor de la Fuente'),
  (4905, 'CL', 'Leonor Gutiérrez'),
  (319, 'CL', 'Lérida'),
  (320, 'CL', 'Linares'),
  (321, 'CL', 'Lizaderas'),
  (322, 'CL', 'Llana de San Juan'),
  (3946, 'PG', 'Llanos del Valle'),
  (323, 'CL', 'Lope de Sosa'),
  (326, 'CL', 'Lucena'),
  (2454, 'CL', 'Luis Braille'),
  (4461, 'CL', 'Luna (la)'),
  (4822, 'PZ', 'Luz del Valle'),
  (4495, 'PZ', 'Macarena (de la)'),
  (4460, 'CL', 'Macias (los)'),
  (330, 'CL', 'Madre de Dios'),
  (4666, 'CL', 'Madre Inés de Jesús'),
  (332, 'CL', 'Madre Soledad Torres Acosta'),
  (4797, 'CL', 'Madre Teresa de Calcuta'),
  (2253, 'CR', 'Madrid'),
  (4161, 'AV', 'Madrid (de)'),
  (335, 'CL', 'Maestra'),
  (336, 'CL', 'Maestro Bartolomé'),
  (337, 'CL', 'Maestro Cebrian'),
  (338, 'CL', 'Maestro Macias'),
  (4667, 'CL', 'Maestro Manuel Moya'),
  (4169, 'CL', 'Maestro Sapena'),
  (4459, 'PZ', 'Magdalena (de la)'),
  (341, 'CL', 'Magdalena Alta'),
  (342, 'CL', 'Magdalena Baja'),
  (343, 'CL', 'Magdalena del Prado'),
  (344, 'CL', 'Málaga'),
  (90344, 'CL', 'Málaga (Pte. Tablas)'),
  (2227, 'CL', 'Mancha Real'),
  (345, 'CL', 'Manuel Briceño'),
  (4739, 'CL', 'Manuel Caballero Venzala'),
  (4561, 'CL', 'Manuel de Falla'),
  (347, 'CL', 'Manuel Jontoya'),
  (348, 'CL', 'Manuel Ruiz Córdoba'),
  (4874, 'PQ', 'María Auxiliadora (de)'),
  (558, 'CL', 'María González López y Manuel Beltrán López'),
  (349, 'CL', 'María de Molina'),
  (4886, 'CL', 'María Dolores García-Negrete'),
  (4902, 'CL', 'María Matea Pérez'),
  (4900, 'CL', 'Mariana de Carvajal y Saavedra'),
  (4903, 'CL', 'Mariana Vaca'),
  (4901, 'CL', 'Mariano de Montoya'),
  (4687, 'PA', 'Marmoleja (La) (Jabalcuz)'),
  (4701, 'CL', 'Marmolejo'),
  (2276, 'CL', 'Marques de la Ensenada'),
  (2218, 'CL', 'Marques de Suances'),
  (3941, 'CL', 'Marroquíes Bajos (de)'),
  (352, 'CL', 'Martínez Molina'),
  (353, 'CL', 'Martínez Montañés'),
  (4458, 'CJ', 'Mártires (los)'),
  (4563, 'CL', 'Martos'),
  (4564, 'CL', 'Matabegid'),
  (4906, 'CL', 'Mati Guillén'),
  (4805, 'CL', 'Matrona Mariana Gómez (de la)'),
  (4457, 'PJ', 'Maza'),
  (357, 'CL', 'Melchor Cobo Medina'),
  (4409, 'CL', 'Melilla (de)'),
  (94409, 'CL', 'Melilla (Pte. Tablas)'),
  (360, 'CL', 'Menéndez y Pelayo'),
  (1383, 'TR', 'Menéndez y Pelayo'),
  (2479, 'CL', 'Mengibar'),
  (4493, 'CL', 'Meninas (las)(Las Infantas)'),
  (4456, 'PZ', 'Merced (la)'),
  (4020, 'CL', 'Merced Alta'),
  (4021, 'CL', 'Merced Alta Sin Salida'),
  (362, 'CL', 'Merced Baja'),
  (4455, 'CL', 'Mercedes (las)'),
  (4837, 'CL', 'Mercedes Lamarque'),
  (4565, 'CL', 'Mesa'),
  (367, 'CL', 'Mezquita'),
  (4792, 'CL', 'Miguel Castillejo'),
  (4403, 'CL', 'Miguel Hermoso Díaz (Las Infantas)'),
  (4566, 'CL', 'Miguel Hernández'),
  (4878, 'CL', 'Miguel Mesa Berro'),
  (368, 'CL', 'Miguel Romera'),
  (4376, 'CL', 'Mijas'),
  (369, 'CL', 'Millán de Priego'),
  (4454, 'CL', 'Minas (las)'),
  (4816, 'CL', 'Mirabueno'),
  (3851, 'SN', 'Mirador (El)(Jabalcuz)'),
  (372, 'CL', 'Misericordia'),
  (4757, 'RD', 'Misericordia (de la)'),
  (4692, 'SN', 'Molino (El)(Las Infantas)'),
  (4452, 'CL', 'Molino de Alcantarilla'),
  (4503, 'CL', 'Molino de Condesa'),
  (4451, 'CL', 'Molinos (los)'),
  (4315, 'CT', 'Mono (del) (Pte. Nuevo)'),
  (375, 'CL', 'Montero Moya'),
  (4318, 'PA', 'Morales (los)(Puerto Alto)'),
  (376, 'CL', 'Moreno Castello'),
  (4730, 'CL', 'Mostar'),
  (4668, 'CL', 'Muralla'),
  (382, 'CL', 'Murillo'),
  (4813, 'CL', 'Músico Damián Martínez Linde (del)'),
  (377, 'CL', 'Muñoz Garnica'),
  (3977, 'AV', 'Muñoz Grandes'),
  (4569, 'TR', 'Muñoz Grandes'),
  (4423, 'CL', 'Naranjo'),
  (4421, 'PZ', 'Naranjos (de los)'),
  (383, 'CL', 'Navas de Tolosa'),
  (385, 'CL', 'Neveral'),
  (4703, 'CR', 'Neveral (el)(Cañoquebrado)'),
  (386, 'CL', 'Nicaragua'),
  (4426, 'CL', 'Nogal'),
  (4847, 'CL', 'Notario Alfonso Luis Sánchez Fernández'),
  (4450, 'CL', 'Novias (las)'),
  (389, 'CL', 'Nuestra Señora de Loreto'),
  (390, 'CL', 'Nuestra Señora del Perpetuo Socorro'),
  (391, 'CL', 'Nueva'),
  (392, 'PZ', 'Nueva'),
  (10016, 'PJ', 'Nuyra'),
  (388, 'CL', 'Nuñez de Balboa'),
  (395, 'CL', 'Obispo Aguilar'),
  (396, 'CL', 'Obispo Alonso Suarez'),
  (394, 'CL', 'Obispo Alonso Vera'),
  (397, 'CL', 'Obispo Arquellada'),
  (398, 'CL', 'Obispo Basulto'),
  (399, 'PZ', 'Obispo García de Castro'),
  (400, 'CL', 'Obispo González'),
  (4669, 'CL', 'Obispo Romero Mengibar'),
  (4494, 'CL', 'Obispo Stuñiga (del)'),
  (405, 'CL', 'Olid'),
  (406, 'CL', 'Oliva'),
  (4762, 'RD', 'Olivares (de los)'),
  (10001, 'PO', 'Olivares (los)'),
  (4428, 'CL', 'Olivo'),
  (407, 'CL', 'Onesimo Redondo'),
  (408, 'TR', 'Onesimo Redondo'),
  (409, 'CL', 'Orcera'),
  (410, 'CL', 'Ormendo'),
  (4670, 'CL', 'Ortega Nieto'),
  (960, 'SN', 'Otiñar'),
  (128, 'CR', 'Otiñar'),
  (4916, 'CL', 'Paco Barbotín'),
  (4819, 'CL', 'Paco Manzaneda'),
  (4413, 'CL', 'Padre Grass'),
  (4405, 'CL', 'Padre Ignacio Ellacuria'),
  (413, 'CL', 'Padre Poveda'),
  (4772, 'CL', 'País Vasco (del)'),
  (4449, 'CL', 'Palmas (las)'),
  (4789, 'SN', 'Palmeras (las) (Jabalcuz)'),
  (4570, 'CL', 'Pantano del Tranco'),
  (4571, 'SN', 'Parador de Santa Catalina (Cañoquebrado)'),
  (4671, 'CL', 'Parra (la)'),
  (417, 'CL', 'Parrilla'),
  (4448, 'CL', 'Pasaje (el)'),
  (4324, 'PZ', 'Paso (del)'),
  (4812, 'CL', 'Patrocinio de Biedma (de)'),
  (4447, 'CL', 'Paz (la)'),
  (4574, 'CL', 'Pedro Díaz'),
  (4348, 'CL', 'Pedro Huesa Pérez'),
  (4911, 'PZ', 'Perfumes (de los)'),
  (10014, 'UR', 'Perlas Complejo (las)'),
  (428, 'CL', 'Peru'),
  (429, 'CL', 'Pescadería'),
  (430, 'CL', 'Peso de la Harina'),
  (423, 'CL', 'Peñamefecit'),
  (4446, 'CL', 'Peñas (los)'),
  (4572, 'CL', 'Peñuelas'),
  (4573, 'TR', 'Peñuelas'),
  (432, 'CL', 'Picadero II'),
  (433, 'CL', 'Pilar de la Imprenta'),
  (4223, 'CJ', 'Pilar de la Imprenta'),
  (4432, 'CL', 'Pintor Carmelo Palomino'),
  (4831, 'CL', 'Pintor Cerezo Moreno'),
  (4839, 'CL', 'Pintor Cristóbal Ruiz'),
  (4882, 'CL', 'Pintor José María Tamayo'),
  (4830, 'CL', 'Pintor Lorenzo Goñi'),
  (4834, 'CL', 'Pintor Fausto Olivares'),
  (4832, 'CL', 'Pintor Francisco Baños'),
  (4729, 'CL', 'Pintor Manuel Angeles Ortiz (del)'),
  (4727, 'CL', 'Pintor Manuel Serrano Cuesta (del)'),
  (434, 'CL', 'Pintor Nogue'),
  (4795, 'CL', 'Pintor Pablo Martín del Castillo (del)'),
  (4835, 'CL', 'Pintor Rafael Hidalgo de Caviedes'),
  (4793, 'CL', 'Pintor Rivera'),
  (4575, 'CL', 'Pintor Rodríguez de la Torre'),
  (4542, 'CL', 'Pintor Rufino Martos (del)'),
  (436, 'CL', 'Pintor Zabaleta'),
  (4172, 'CL', 'Pintor Zurbaran'),
  (4672, 'CJ', 'Pintoras (de las)'),
  (437, 'CL', 'Pío XII'),
  (4576, 'CL', 'Pizarro'),
  (4741, 'PZ', 'Planetas (de los)'),
  (4445, 'CL', 'Plata (la)'),
  (4504, 'UR', 'Plaza de la Luna'),
  (4824, 'CL', 'Plaza de Toros'),
  (4500, 'TR', 'Plaza La Corona Primera'),
  (4501, 'TR', 'Plaza La Corona Segunda'),
  (4794, 'CL', 'Poeta Felipe Molina Verdejo (del)'),
  (455, 'CL', 'Porcuna'),
  (4689, 'SN', 'Portazgo (Pte. Sierra)'),
  (456, 'CL', 'Portillo'),
  (4353, 'PZ', 'Portillo de San Jerónimo'),
  (4673, 'CL', 'Portillo de San Jerónimo'),
  (4131, 'SN', 'Portón de los Leones (Pte. Sierra)'),
  (457, 'CL', 'Positillo'),
  (4444, 'PZ', 'Posito (el)'),
  (4083, 'CL', 'Pozo'),
  (4317, 'PA', 'Pozuela (Grañena)'),
  (460, 'CL', 'Primero de Abril'),
  (4765, 'CL', 'Principado de Asturias (del)'),
  (462, 'CL', 'Príncipe Alfonso'),
  (4726, 'CL', 'Profesor Alfonso Sancho Saez'),
  (4880, 'CL', 'Profesor Luis Coronas Tejada'),
  (958, 'CR', 'Puente de la Sierra'),
  (90958, 'SN', 'Puente de la Sierra (Pte. de la Sierra)'),
  (1067, 'SN', 'Puente Jontoya (Pte. Jontoya)'),
  (1618, 'SN', 'Puente Nuevo (Pte. Nuevo)'),
  (1577, 'SN', 'Puente Tablas (Galapagar)'),
  (4429, 'CL', 'Puerta Aceituno'),
  (468, 'CL', 'Puerta de Martos'),
  (4263, 'TR', 'Puerta de Martos Primera'),
  (4269, 'TR', 'Puerta de Martos Segunda'),
  (469, 'CL', 'Puerta del Angel'),
  (470, 'CL', 'Puerta del Sol'),
  (4193, 'CR', 'Puerto Alto (Puerto Alto)'),
  (4351, 'CL', 'Ntro. Padre Jesús de la Piedad (de)'),
  (4352, 'PZ', 'Purísima Concepción'),
  (472, 'CL', 'Quero'),
  (4683, 'SN', 'Quiebracantaros (Pte. Jontoya)'),
  (473, 'CL', 'Ramón Espantaleón'),
  (474, 'CL', 'Ramón y Cajal'),
  (475, 'CL', 'Real'),
  (4771, 'CL', 'Región de Murcia (de la)'),
  (4863, 'PZ', 'Reina del Salvador'),
  (4674, 'CL', 'Reja de la Capilla'),
  (477, 'CL', 'Remojadero del Pescado'),
  (478, 'CL', 'República Argentina'),
  (479, 'CL', 'Reventón'),
  (480, 'CL', 'Rey Alhamar'),
  (2928, 'CL', 'Rey Ali'),
  (481, 'CL', 'Rey Don Pedro'),
  (482, 'CL', 'Reyes Católicos'),
  (4581, 'CL', 'Río Segura'),
  (4769, 'CL', 'Rioja (de la)'),
  (484, 'CL', 'Rivera'),
  (486, 'CL', 'Roldán y Marín'),
  (4430, 'CL', 'Romeros (los)'),
  (4417, 'CL', 'Ronda'),
  (94417, 'CL', 'Ronda (Pte. Tablas)'),
  (4849, 'CL', 'Ronda de Marroquies'),
  (4662, 'PR', 'Ronda General Rodrigo'),
  (4907, 'CL', 'Rosa Butler y Mendieta'),
  (4791, 'PZ', 'Rosales'),
  (10015, 'PO', 'Rosales (los)'),
  (4860, 'CL', 'Rosalía de Castro'),
  (4022, 'CL', 'Rostro'),
  (4023, 'PZ', 'Rostro (del)'),
  (492, 'CL', 'Rueda Sin Salida'),
  (493, 'AV', 'Ruiz Jiménez'),
  (495, 'CL', 'Ruiz Romero'),
  (540, 'CL', 'Sagrada Familia'),
  (541, 'CL', 'Sagrado Corazón de Jesús'),
  (542, 'CL', 'Salido'),
  (543, 'CL', 'Salineros'),
  (4419, 'CL', 'Salobreja'),
  (544, 'CL', 'Salsipuedes'),
  (545, 'CL', 'Salvador Vicente de la Torre'),
  (2512, 'TR', 'Salvador Vicente de la Torre'),
  (3325, 'PZ', 'San Agustín (de)'),
  (4582, 'CL', 'San Alejandro'),
  (4583, 'CL', 'San Amadeo'),
  (3360, 'CL', 'San Andrés'),
  (4584, 'CL', 'San Aniceto'),
  (501, 'CL', 'San Antón'),
  (2074, 'CL', 'San Antonio'),
  (4585, 'CL', 'San Balbino'),
  (3309, 'CL', 'San Bartolomé'),
  (3527, 'PZ', 'San Bartolomé (de)'),
  (4587, 'CJ', 'San Benito (de)'),
  (3781, 'PZ', 'San Bernardo (de)'),
  (4588, 'CL', 'San Blas'),
  (2051, 'CL', 'San Carlos'),
  (4589, 'CL', 'San Claudio'),
  (3446, 'CL', 'San Clemente'),
  (4590, 'CL', 'San Eladio'),
  (4433, 'CL', 'San Eufrasio'),
  (3981, 'CL', 'San Felipe'),
  (864, 'PZ', 'San Felix (de)'),
  (1193, 'CL', 'San Fernando'),
  (4592, 'PJ', 'San Francisco'),
  (3474, 'PZ', 'San Francisco (de)'),
  (4675, 'CL', 'San Francisco de Asís'),
  (2116, 'CL', 'San Francisco Javier'),
  (4594, 'CL', 'San Gervasio'),
  (4728, 'CL', 'San Ignacio (de)'),
  (1167, 'PZ', 'San Ildefonso (de)'),
  (2282, 'PZ', 'San Isidro (de)(Las Infantas)'),
  (4596, 'CL', 'San Ismael'),
  (4361, 'TR', 'San Joaquín'),
  (4597, 'CL', 'San Joaquín'),
  (1278, 'CL', 'San José'),
  (3256, 'CL', 'San Juan'),
  (4598, 'PZ', 'San Juan (de)'),
  (2999, 'CL', 'San Juan de Dios'),
  (2953, 'PZ', 'San Juan de Dios (de)'),
  (1795, 'CL', 'San Juan de la Cruz'),
  (3564, 'CL', 'San Lorenzo'),
  (2500, 'CL', 'San Lucas'),
  (4599, 'CL', 'San Marcelo'),
  (2938, 'CL', 'San Miguel'),
  (2989, 'PZ', 'San Miguel (de)'),
  (533, 'TR', 'San Pablo'),
  (3761, 'CL', 'San Pablo'),
  (4676, 'CL', 'San Pascual Bailón'),
  (4600, 'CL', 'San Patricio'),
  (2601, 'CL', 'San Rafael'),
  (939, 'CL', 'San Ramón'),
  (1339, 'CL', 'San Roque'),
  (1381, 'PJ', 'San Roque'),
  (1375, 'PZ', 'San Roque (de)'),
  (4700, 'CL', 'San Rufino'),
  (4601, 'CL', 'San Salvio'),
  (3881, 'CL', 'San Sebastián'),
  (4602, 'SN', 'Sanatorio Dr. Sagaz (Cañoquebrado)'),
  (563, 'TR', 'Santa Barbara'),
  (3176, 'CL', 'Santa Barbara'),
  (1373, 'CL', 'Santa Brigida'),
  (1248, 'CL', 'Santa Catalina'),
  (932, 'CL', 'Santa Cecilia'),
  (3292, 'CL', 'Santa Clara'),
  (883, 'CL', 'Santa Cristina'),
  (1062, 'CL', 'Santa Cruz'),
  (4748, 'TR', 'Santa Cruz Primera'),
  (4270, 'TR', 'Santa Cruz Segunda'),
  (2602, 'CL', 'Santa Elena'),
  (2588, 'PZ', 'Santa Isabel (de)'),
  (324, 'CL', 'Santa Joaquina de Vedruna'),
  (2942, 'PZ', 'Santa Luisa de Marillac (de)'),
  (739, 'PZ', 'Santa María (de)'),
  (1749, 'CL', 'Santa María del Valle'),
  (3922, 'GT', 'Santa María Micaela (de)'),
  (1333, 'CL', 'Santa Rita'),
  (2235, 'CL', 'Santa Teresa de Jesús'),
  (2940, 'CL', 'Santa Ursula'),
  (547, 'CL', 'Santiago'),
  (548, 'PZ', 'Santiago (de)'),
  (549, 'CL', 'Santísima Trinidad'),
  (550, 'CL', 'Santisteban'),
  (2985, 'CL', 'Santo Domingo'),
  (2994, 'PZ', 'Santo Domingo (de)'),
  (2967, 'CL', 'Santo Domingo Bajo'),
  (1962, 'CL', 'Santo Reino'),
  (2583, 'CL', 'Santo Rostro'),
  (1415, 'CL', 'Santo Tomas'),
  (551, 'CL', 'Santuario'),
  (552, 'CL', 'Sargentos Provisionales'),
  (4422, 'CL', 'Sauce'),
  (553, 'CL', 'Sebastián Martínez'),
  (554, 'CL', 'Sedeño'),
  (4610, 'CL', 'Segovia'),
  (4031, 'CL', 'Senda de los Huertos'),
  (556, 'CL', 'Sevilla'),
  (90556, 'CL', 'Sevilla (Pte. Tablas)'),
  (557, 'CL', 'Sierra Mágina'),
  (4749, 'CL', 'Sixto Cámara'),
  (4785, 'CL', 'Solidaridad (de la)'),
  (560, 'CL', 'Soria de San Juan'),
  (4437, 'CL', 'Subida al Tambor'),
  (4753, 'RD', 'Sur'),
  (202, 'CL', 'Tablerón'),
  (4374, 'CL', 'Tejares (de los)'),
  (4319, 'PA', 'Tejares (los)(Pte. Jontoya)'),
  (2982, 'CL', 'Telégrafos'),
  (586, 'CL', 'Teniente Anguita Roldán'),
  (587, 'CL', 'Teniente Bago'),
  (588, 'CL', 'Teniente Escobedo'),
  (589, 'CL', 'Teniente Ruano'),
  (590, 'CL', 'Teodoro Calvache'),
  (2217, 'CL', 'Tetuan'),
  (591, 'CL', 'Tinajeros'),
  (4613, 'CL', 'Tiro Nacional'),
  (4335, 'SB', 'Tiro Nacional'),
  (4614, 'TR', 'Tiro Nacional Segunda'),
  (4784, 'CL', 'Tolerancia (de la)'),
  (4349, 'CL', 'Tomas Moreno Bravo'),
  (4336, 'CL', 'Tomillo'),
  (4615, 'CL', 'Toro'),
  (4616, 'CL', 'Torre del Homenaje'),
  (4356, 'CL', 'Torredelcampo'),
  (2238, 'CL', 'Torredonjimeno'),
  (595, 'CL', 'Torreperea'),
  (596, 'CR', 'Torrequebradilla'),
  (80596, 'CR', 'Torrequebradilla (Galapagar)'),
  (90596, 'CR', 'Torrequebradilla (Puente Tablas)'),
  (4438, 'CL', 'Torres (los)'),
  (599, 'CL', 'Tres Morillas'),
  (600, 'CL', 'Triana'),
  (4617, 'CL', 'Trochas (las)'),
  (601, 'PZ', 'Troyano Salaverry (de)'),
  (4143, 'SN', 'Trucha (la)-Apartamentos (Pte. Sierra)'),
  (602, 'CL', 'Ubeda'),
  (4803, 'CL', 'Unicef (de la)'),
  (4338, 'AV', 'Universidad (de la)'),
  (4440, 'CL', 'Uribes (los)'),
  (606, 'CL', 'Vacas'),
  (4618, 'CL', 'Vacas de San Juan'),
  (4264, 'TR', 'Vacas Primera'),
  (4271, 'TR', 'Vacas Segunda'),
  (4788, 'SN', 'Vaciacostales (Grañena)'),
  (4516, 'UR', 'Valdeastillas (La Imora)'),
  (4688, 'PA', 'Valdecañas (Pte. Sierra)'),
  (4173, 'CL', 'Valdés Leal'),
  (4619, 'CL', 'Valencia'),
  (4754, 'RD', 'Valle (del)'),
  (4536, 'PO', 'Valle Edif. Melero (del)'),
  (10013, 'PO', 'Valle Resto (el)'),
  (4608, 'PO', 'Valle Sector II (del)'),
  (4248, 'PO', 'Valle Sector III (del)'),
  (4249, 'PO', 'Valle Sector IV (del)'),
  (4250, 'PO', 'Valle Sector V (del)'),
  (4609, 'PO', 'Valle Sector VI (del)'),
  (4252, 'PO', 'Valle Sector VIII (del)'),
  (609, 'CL', 'Vallehermoso'),
  (610, 'CL', 'Valparaíso'),
  (4344, 'UR', 'Valparaíso (Pte. Sierra)'),
  (4620, 'CL', 'Vandelvira'),
  (612, 'CL', 'Vargas'),
  (4157, 'SN', 'Vega de la Reina (Pte. Nuevo)'),
  (613, 'CL', 'Velázquez'),
  (614, 'CL', 'Venezuela'),
  (4514, 'CL', 'Venta de Cañero'),
  (2860, 'SN', 'Ventosilla (Ventosilla)'),
  (4826, 'CL', 'Vereda (de la)'),
  (616, 'CL', 'Vergara'),
  (617, 'CL', 'Vicario'),
  (4156, 'CL', 'Vicente Montuno Morente'),
  (4408, 'SN', 'Villa Carlota (La Imora)'),
  (4257, 'SN', 'Villa Isabel (Pte. Sierra)'),
  (94190, 'SN', 'Villa Pilar (Almenara)'),
  (4190, 'SN', 'Villa Pilar (Pte. Sierra)'),
  (4622, 'CL', 'Villacarrillo'),
  (4498, 'PZ', 'Villalobos (de)'),
  (2861, 'SN', 'Villar de Cuevas (Villar De Cuevas)'),
  (4151, 'CR', 'Villares (Los)(Jabalcuz)'),
  (4441, 'CR', 'Villargordo (Las Infantas)'),
  (2213, 'CL', 'Villatorres'),
  (622, 'CL', 'Virgen Blanca'),
  (4384, 'UR', 'Virgen Blanca (La Imora)'),
  (4623, 'PZ', 'Virgen de Alharilla'),
  (4624, 'PZ', 'Virgen de Araceli'),
  (4625, 'PZ', 'Virgen de Covadonga'),
  (4626, 'CL', 'Virgen de Cuadros'),
  (4627, 'PZ', 'Virgen de Fátima'),
  (4628, 'CL', 'Virgen de Guadalupe'),
  (628, 'CL', 'Virgen de la Cabeza'),
  (629, 'CL', 'Virgen de la Capilla'),
  (4761, 'PZ', 'Virgen de la Esperanza'),
  (4629, 'PZ', 'Virgen de la Estrella'),
  (4630, 'PZ', 'Virgen de la Fuensanta'),
  (632, 'CL', 'Virgen de la Paloma'),
  (4699, 'PZ', 'Virgen de la Paz'),
  (4631, 'CL', 'Virgen de la Victoria'),
  (4632, 'PZ', 'Virgen de la Villa'),
  (4633, 'CL', 'Virgen de las Angustias'),
  (4242, 'CL', 'Virgen de las Nieves'),
  (4634, 'PZ', 'Virgen de Linarejos'),
  (637, 'PZ', 'Virgen de los Desamparados'),
  (4635, 'PZ', 'Virgen de los Remedios'),
  (4636, 'CL', 'Virgen de los Reyes'),
  (4637, 'PZ', 'Virgen de Lourdes'),
  (4638, 'CL', 'Virgen de Monserrat'),
  (642, 'CL', 'Virgen de Tiscar'),
  (4640, 'CL', 'Virgen del Alcázar'),
  (643, 'CL', 'Virgen del Carmen'),
  (4705, 'CL', 'Virgen del Collado'),
  (645, 'CL', 'Virgen del Mar'),
  (646, 'CL', 'Virgen del Pilar'),
  (2585, 'TR', 'Virgen del Pilar'),
  (4641, 'PS', 'Virgen del Rocío'),
  (648, 'CL', 'Virgen Inmaculada'),
  (4790, 'TR', 'Virgen Inmaculada'),
  (650, 'TR', 'Virgen Milagrosa'),
  (649, 'CL', 'Virgen Milagrosa'),
  (651, 'CL', 'Virgilio Anguita'),
  (4742, 'PZ', 'Zodiaco (del)'),
  (652, 'CL', 'Zumbajarros'),
  (653, 'TR', 'Zumbajarros'),
  (4507, 'CL', 'Zumel')
on conflict (source_code, via_type, name) do nothing;

commit;
